### ISSUE TITLE
Resource Management Tweaks

### ISSUE THREAD

**Issue by deternitydx** [snac-cooperative/snac#144]
We might want to look into trimming the abstract on the search page to a set length with an ellipsis; on my 13" laptop, it scrolls quite a bit.  (I searched for "google" and there were a few long abstracts).

Also, we need to put the feedback scripts on the resource management pages.  (They are the html2canvas and feedback files).

**Comment by glassjoseph** [comment]
Good idea. I'd like to widen the abstract column as well. In the meantime, I'll make the search results more like a summary, since we now have the view page as an optional expansion. 

I'll make sure to add in the feedback scripts into resource search, edit, and view as well.

**Comment by glassjoseph** [comment]
There's also the question of whether to just add the Display Entry, or replace Title with Display Entry, etc.
