### ISSUE TITLE
Snac-dev should display all tabs

### ISSUE THREAD

**Issue by glassjoseph** [snac-cooperative/snac#191]
The new view page doesn't show tabs that don't have content. 
For example, on this [page,](https://snac-dev.iath.virginia.edu/view/52334549) we only see Bioghist and Resources tab. 
![image](https://user-images.githubusercontent.com/17987273/55807305-fd7b3e80-5aaf-11e9-9148-fa0ce4f2c520.png)

We'd like it to show all tabs, regardless of whether they're empty or not. Like the current [detailed page](https://snaccooperative.org/details/52334549/7651158).
![image](https://user-images.githubusercontent.com/17987273/55807427-30253700-5ab0-11e9-825e-32d540a81031.png)

**Comment by deternitydx** [comment]
Could you use some kind of disabled attribute so that they're shown but known to be empty?  (Save the user the time of clicking on them only to realize they're empty.  I think that's why they were hidden to start with.)
