### ISSUE TITLE
Diacritics in Names

### ISSUE THREAD

**Issue by dinaherbert** [snac-cooperative/snac#199]
**Is your feature request related to a problem? Please describe.**
Searching for names with diacritics (in preferred name) is not easy; if it's not the "correct" diacritics you can't get what you want

**Describe the solution you'd like**
We train new editors to put in different name variations with no diacritics but I'm not sure if they are searchable or if we can make it better for searching

**Search** 
If you search without a diacritic (Bronte NOT Brontë) you don't get results you expect
![Capture](https://user-images.githubusercontent.com/16778324/56608380-a3fb2f80-65d8-11e9-87de-36f20e7c1472.PNG)
![Capture1](https://user-images.githubusercontent.com/16778324/56608373-a198d580-65d8-11e9-868a-fd8ae7100251.PNG)

**Autofill**
It will autofill with diacritic (Brontë) which is good for a diacritic towards the end but not towards the beginning
![Capture2](https://user-images.githubusercontent.com/16778324/56608374-a198d580-65d8-11e9-81cf-4b4c2b3d007a.PNG)

**Advanced Search**
It will give you a positive result from a biography probably because Bronte is spelled there with no diacritic. BUT, even though there are alternative names with no diacritics it doesn't show up with just an advanced search
![Capture3](https://user-images.githubusercontent.com/16778324/56608375-a198d580-65d8-11e9-91be-efc8e0e5ba0b.PNG)
![Capture4](https://user-images.githubusercontent.com/16778324/56608376-a198d580-65d8-11e9-8464-4c6809cfebd7.PNG)

**Alternative names**
![Capture5](https://user-images.githubusercontent.com/16778324/56608372-a198d580-65d8-11e9-91dd-3cf9752f8240.PNG)

**Comment by glassjoseph** [comment]
We could strip out the diacritics, but that would create the opposite problem. 

The best approach is probably adding a `asciifolding` [character filter](https://www.elastic.co/guide/en/elasticsearch/guide/current/asciifolding-token-filter.html#_retaining_meaning). We'd need to index the name twice, once with the diacritic, once without, so it can be found with either version. Using `preserve_original` might also be worth it for this use case.

We should also look into the similar problem of punctuation (periods, commas, etc) in names when we fix this issue.

**Comment by glassjoseph** [comment]
Daniel adds that it'd be best to follow [NACO normalization rules](http://www.loc.gov/aba/pcc/naco/normrule-2.html) if at all possible, as that should give us good search results with clear, well-defined rules.

**Comment by deternitydx** [comment]
@glassjoseph We should also fold in the alternative names into the main name index and then rebuild.  It would take a bit of work on our side (including the reconciliation engine) to solely use the combined name index, but I think it's worth it.
