### ISSUE TITLE
Javascript Name Parser

### ISSUE THREAD

**Issue by deternitydx** [snac-cooperative/snac#67]
Name entries: if one has a full name heading in a source, where the source is in a good status (parseable), can we have a widget that will parse it into components and insert it into the edit page appropriately?
     - @wnmartin suggests: a little "parse it" button that would open up a widget and give you a place to paste a name and see how it would be parsed.
     - One idea:  "parsing" modal box that you could enter/paste a name in and click "parse".  It would then give possible parsings.  The user could choose one that looks correct and click the "Use it" button to insert it into the edit page.  If it isn't perfect, the user could then update and modify in the edit page.

**Comment by dpitti** [comment]
This needs to be moved from Wish List to the To Do list, as it is in the proposal as an enhancement.

**Comment by deternitydx** [comment]
@glassjoseph has written this and it's on its way to being included.  Closing issue.
