### ISSUE TITLE
HRT alternative names

### ISSUE THREAD

**Issue by dpitti** [snac-cooperative/snac#76]
The alternative names list the preferred name as well as all of the other names. I suggest changing the "alternative names" to "other names," and listing only the non-preferred names. Rationale: we use "authoritative" and "alternative" formally in relation to rules, and then apart from this, preferred for the name used in the display. "Other names" will avoid terminology confusion. And the names listed under other should be only the names not preferred.

**Comment by deternitydx** [comment]
@dpitti is this something we should address now or move to the point when we are looking at redesigning the HRT interface?

**Comment by dpitti** [comment]
It will be more efficient to address at the same time as redesigning the HRT. It is not a burning issue. I just thought I would note it because it occurs to me over and over and I never remember to mention it.

**Comment by deternitydx** [comment]
@dpitti I had forgotten about this issue.  Jerry asked a similar question earlier this week.  I did a little trick on the HRT page that should have removed the preferred name from the alternative names list.  It should be up on the alpha branch.

What I didn't do was rename the link.  Is it alright to close this ticket, and address renaming while performing the redesign, or should I rename the link now?
