### ISSUE TITLE
Change type of entity

### ISSUE THREAD

**Issue by dpitti** [snac-cooperative/snac#78]
In dev. Attempted to change one George Washington typed as corporate body to person. Save and continue worked fine. Save and publish gave an "Oops!" Attempted the same with one typed family. Same result. Though when returning to browse, both entries seemed to have been effectively changes. Mistyping is a relatively common error, and so it needs to be possible to change type. In almost all cases, the mis-type entity is likely to be a very sparse IC.

**Comment by deternitydx** [comment]
@dpitti please try this on http://snac-dev.iath.virginia.edu.  I think this was due to the development version on snac-dev being down.

**Comment by deternitydx** [comment]
@dpitti thanks for checking.  You had mentioned it to me, but I wanted to follow up before closing the issue on Github.

**Comment by dpitti** [comment]
Yes, due to development version. All fine in  http://snac-dev.iath.virginia.edu, as far as I could determine. No errors thrown.
