### ISSUE TITLE
Repository Searching and New Resource

### ISSUE THREAD

**Issue by deternitydx** [snac-cooperative/snac#79]
Users were having a lot of trouble putting the SNAC ID into the Repository SNAC ID field in the edit interface, when creating a new resource.  They were entering names of repositories as well as ARK ids.

We need to replace the box with a searchable dropdown so that users can more easily find repositories.

**Comment by deternitydx** [comment]
We have a few options to accomplish this, and a few stages:

- [ ] Add the repository id (or id, nameEntry) to the ES resource cache
    - A question here is what happens when the Postgres constellation gets merged?
- [ ] Create a secondary index of holding repositories
    - This is either for Postgres or ES.  If alphabetical is okay, then Postgres is preferred, like the name index for browsing
- [ ] An **alternative** to the other two: Use Neo4J to add a third relationship type (HOLDING) and have it relate ICs to resources.
    - This may be preferred to all others, because we can have Neo4J search for any IC that holds a particular resource as well as faster querying of who "holds" what ICs.

**Comment by deternitydx** [comment]
This should be a Neo4J query with an additional "holding" relation type between documents and constellations.  It should be easy to implement.

We also need to add the flag on the other pages (view, browse, search) if a particular Constellation is a holding repository.

**Comment by dpitti** [comment]
What is the status of this?

**Comment by deternitydx** [comment]
On development and moving to production 5/31
