### ISSUE TITLE
List all currently locked constellations

### ISSUE THREAD

**Issue by deternitydx** [snac-cooperative/snac#82]
In helping out Doug with the CBW ingest scripts, I found another useful administrator page we should develop.  Currently, you can choose a user and then list all the constellations they have checked out.  But, there needs to be a page with all constellations checked out, in case the user doesn't know who checked them out.

In the database backup used to create the sandbox, Dina had 18 constellations checked out, but we didn't know that.  A page like this would aid in finding out that information.

The SQL to get most of the data from the VH table is:
```sql
select a.id as ic_id, a.version, a.status, a.user_id, u.fullname 
    from version_history a, 
        (select id as ic_id, max(version) as version from version_history group by id) b, 
        appuser u 
    where a.id = b.ic_id and a.version = b.version and a.user_id = u.id 
        and a.status in ('currently editing', 'needs review', 
            'locked editing', 'change locks');
```

**Comment by deternitydx** [comment]
@glassjoseph This might be a good next feature to look at.  It's independent of other functionality (completely new), and goes from the webUI all the way down to the Server, DBUtil, and SQL.  I can point you at some examples of similar webui templates, server calls, and DBUtil functions.

**Comment by deternitydx** [comment]
@glassjoseph We finished this, right?  It was just a little slow loading from the database?

**Comment by glassjoseph** [comment]
Yeah, it's written, just takes a long, long time to load.
